// front/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-card">
      <h1 class="login-title">IES CRM</h1>
      <p class="login-subtitle">Вход в систему</p>
      
      <form @submit.prevent="handleLogin" class="login-form">
        <div v-if="authStore.error" class="error-message">
          {{ authStore.error }}
        </div>
        
        <div class="form-group">
          <label for="email">Email</label>
          <input
            id="email"
            v-model="email"
            type="email"
            required
            placeholder="Адрес электронной почты"
            class="form-input"
            :disabled="authStore.loading"
          />
        </div>
        
        <div class="form-group">
          <label for="password">Пароль</label>
          <input
            id="password"
            v-model="password"
            type="password"
            required
            placeholder="Пароль"
            class="form-input"
            :disabled="authStore.loading"
          />
        </div>
        
        <button
          type="submit"
          class="login-button"
          :disabled="authStore.loading"
        >
          <span v-if="authStore.loading">Вход...</span>
          <span v-else>Войти</span>
        </button>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const router = useRouter()
const authStore = useAuthStore()

const email = ref('')
const password = ref('')

async function handleLogin() {
  try {
    await authStore.login(email.value, password.value)
    router.push('/')
  } catch (error) {
    // Ошибка уже обработана в store
  }
}
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: #fff;
  padding: 2rem;
  position: relative;
}

.login-card {
  background: #fff;
  border: 2px solid #e8f5e9;
  border-radius: 16px;
  box-shadow: 0 8px 30px rgba(66, 184, 131, 0.2);
  padding: 2.5rem;
  width: 100%;
  max-width: 400px;
  transition: all 0.3s ease;
  transform: translateY(-15%);
  position: relative;
}

@media (max-width: 768px) {
  .login-container {
    padding: 1rem;
  }
  
  .login-card {
    padding: 2rem;
    transform: translateY(0);
    max-width: 100%;
  }
}

@media (max-width: 480px) {
  .login-container {
    padding: 0.75rem;
  }
  
  .login-card {
    padding: 1.5rem;
    border-radius: 12px;
  }
}

.login-card:hover {
  border-color: #42b883;
  box-shadow: 0 8px 30px rgba(66, 184, 131, 0.25);
}

.login-title {
  color: #2c3e50;
  text-align: center;
  margin-bottom: 0.5rem;
  font-size: 2rem;
  font-weight: 700;
}

.login-subtitle {
  color: #7f8c8d;
  text-align: center;
  margin-bottom: 2rem;
  font-size: 1rem;
}

@media (max-width: 768px) {
  .login-title {
    font-size: 1.75rem;
  }
  
  .login-subtitle {
    font-size: 0.95rem;
    margin-bottom: 1.5rem;
  }
}

@media (max-width: 480px) {
  .login-title {
    font-size: 1.5rem;
  }
  
  .login-subtitle {
    font-size: 0.9rem;
    margin-bottom: 1.25rem;
  }
}

.login-form {
  margin-bottom: 1.5rem;
}

.form-group {
  margin-bottom: 1.5rem;
}

.form-group label {
  display: block;
  margin-bottom: 0.5rem;
  color: #2c3e50;
  font-weight: 500;
  font-size: 0.9rem;
}

.form-input {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #e0e0e0;
  border-radius: 6px;
  font-size: 1rem;
  transition: border-color 0.2s, box-shadow 0.2s;
}

@media (max-width: 480px) {
  .form-input {
    padding: 0.65rem;
    font-size: 0.95rem;
  }
}

.form-input:focus {
  outline: none;
  border-color: #42b883;
  box-shadow: 0 0 0 3px rgba(66, 184, 131, 0.1);
}

.form-input:disabled {
  background-color: #f5f5f5;
  cursor: not-allowed;
}

.error-message {
  background-color: #fee;
  color: #e74c3c;
  padding: 0.75rem;
  border-radius: 6px;
  margin-bottom: 1rem;
  font-size: 0.9rem;
  border: 1px solid #e74c3c;
}

.login-button {
  width: 100%;
  padding: 0.75rem;
  background: #42b883;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  transition: background-color 0.2s, transform 0.1s;
}

@media (max-width: 480px) {
  .login-button {
    padding: 0.65rem;
    font-size: 0.95rem;
  }
}

.login-button:hover:not(:disabled) {
  background: #35a372;
  transform: translateY(-1px);
}

.login-button:active:not(:disabled) {
  transform: translateY(0);
}

.login-button:disabled {
  background: #95a5a6;
  cursor: not-allowed;
}

.login-hint {
  background-color: #f8f9fa;
  border-radius: 6px;
  padding: 1rem;
  font-size: 0.85rem;
  color: #7f8c8d;
  border: 1px solid #e0e0e0;
}

.login-hint p {
  margin: 0.25rem 0;
}

.login-hint p:first-child {
  font-weight: 600;
  margin-bottom: 0.5rem;
  color: #2c3e50;
}

.login-hint strong {
  color: #2c3e50;
}
</style>

// react-front/app/routes/login.tsx
import { useState } from 'react';
import type { FormEvent } from 'react';
import { useNavigate, redirect } from 'react-router';
import { useAuth } from '../contexts/AuthContext';
import type { Route } from './+types/login';
import './login.css';

export function meta({}: Route.MetaArgs) {
  return [
    { title: 'Вход в систему - IES CRM' },
    { name: 'description', content: 'Вход в систему IES CRM' },
  ];
}

export async function clientLoader({}: Route.ClientLoaderArgs) {
  // clientLoader выполняется только на клиенте, но добавляем проверку для безопасности
  if (typeof window !== 'undefined' && window.localStorage) {
    const token = localStorage.getItem('auth_token');
    if (token) {
      throw redirect('/');
    }
  }
  return null;
}

export default function Login() {
  const navigate = useNavigate();
  const auth = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleLogin = async (e: FormEvent) => {
    e.preventDefault();
    try {
      await auth.login(email, password);
      navigate('/');
    } catch (error) {
      // Ошибка уже обработана в context
    }
  };

  return (
    <div className="login-container">
      <div className="login-card">
        <h1 className="login-title">IES CRM</h1>
        <p className="login-subtitle">Вход в систему</p>
        
        <form onSubmit={handleLogin} className="login-form">
          {auth.error && (
            <div className="error-message">
              {auth.error}
            </div>
          )}
          
          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              placeholder="Адрес электронной почты"
              className="form-input"
              disabled={auth.loading}
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="password">Пароль</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              placeholder="Пароль"
              className="form-input"
              disabled={auth.loading}
            />
          </div>
          
          <button
            type="submit"
            className="login-button"
            disabled={auth.loading}
          >
            {auth.loading ? 'Вход...' : 'Войти'}
          </button>
        </form>
      </div>
    </div>
  );
}
